import fs from 'node:fs';
import path from 'node:path';

import getPackageBaseUrl from '../config/get-package-base-url';
import getSelfRoot from '../config/get-self-root';

const selfRegisterFile = 'plugins.ts';

/**
 * Register plugins
 * @returns {void}
 */
const cleanPluginsRegistry = (): void => {
  const getSelfBaseUrl = getPackageBaseUrl(getSelfRoot());
  const selfRegisterFilePath = path.join(getSelfRoot(), getSelfBaseUrl, selfRegisterFile);

  const fileContent =
    "'use no-plugins';\n\n" +
    '/* eslint-disable import/no-extraneous-dependencies */\n\n' +
    '// Do not edit this file manually, it is auto-generated by catalyst-pluginizr\n\n';

  fs.writeFileSync(selfRegisterFilePath, fileContent);
};

export default cleanPluginsRegistry;
